gurdy:

# Publish all joint states -----------------------------------

    joint_state_controller:

        type: joint_state_controller/JointStateController

        publish_rate: 50

# Position Controllers ---------------------------------------

    head_upperleg_joint_position_controller:

        type: effort_controllers/JointPositionController

        joint: 
          -  head_upperlegM1_joint
          -  head_upperlegM2_joint
          -  head_upperlegM3_joint

        gains:
          head_upperlegM1_joint:   {p: 1.0, i: 1.0, d: 0.1, i_clamp: 0.0}
          head_upperlegM2_joint:   {p: 1.0, i: 1.0, d: 0.1, i_clamp: 0.0}
          head_upperlegM3_joint:   {p: 1.0, i: 1.0, d: 0.1, i_clamp: 0.0}
     
# To add more just add them here as the first one
   
    upperleg_lowerleg_joint_position_controller:
        type: effort_controllers/JointPositionController

        joint: 
          -  upperlegM1_lowerlegM1_joint
          -  upperlegM2_lowerlegM2_joint
          -  upperlegM3_lowerlegM3_joint

        gains:
          upperlegM1_lowerlegM1_joint:   {p: 1.0, i: 1.0, d: 0.1, i_clamp: 0.0}
          upperlegM2_lowerlegM2_joint:   {p: 1.0, i: 1.0, d: 0.1, i_clamp: 0.0}
          upperlegM3_lowerlegM3_joint:   {p: 1.0, i: 1.0, d: 0.1, i_clamp: 0.0}
