robot:
  robot_joint_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
      - joint_s
      - joint_l
      - joint_e
      - joint_u
      - joint_r
      - joint_b

    gains:
      joint_s:   {p: 100.0, i: 10.0, d: 0.1, i_clamp: 0.0}
      joint_l:   {p: 100.0, i: 10.0, d: 0.1, i_clamp: 0.0}
      joint_e:   {p: 100.0, i: 10.0, d: 0.1, i_clamp: 0.0}
      joint_u:   {p: 100.0, i: 10.0, d: 0.1, i_clamp: 0.0}
      joint_r:   {p: 100.0, i: 10.0, d: 0.1, i_clamp: 0.0}
      joint_b:   {p: 100.0, i: 10.0, d: 0.1, i_clamp: 0.0}

